"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import Any, TYPE_CHECKING

from mag3nt.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .apikey import APIKey, APIKeyStatus, APIKeyTypedDict
    from .balance import (
        Balance,
        BalanceAvailable,
        BalanceAvailableTypedDict,
        BalanceTypedDict,
        TotalAllocated,
        TotalAllocatedTypedDict,
        TotalFunded,
        TotalFundedTypedDict,
        TotalSpent,
        TotalSpentTypedDict,
        TotalWithdrawn,
        TotalWithdrawnTypedDict,
    )
    from .balanceerror import (
        BalanceErrorAvailable,
        BalanceErrorAvailableTypedDict,
        Requested,
        RequestedTypedDict,
    )
    from .card import (
        BalanceUnion,
        BalanceUnionTypedDict,
        Card,
        CardStatus,
        CardTypedDict,
        LimitAmount,
        LimitAmountTypedDict,
        Remaining,
        RemainingTypedDict,
        SingleUse,
    )
    from .paylink import (
        PayLink,
        PayLinkAmount,
        PayLinkAmountTypedDict,
        PayLinkStatus,
        PayLinkTypedDict,
    )
    from .paymentheader import PaymentHeader, PaymentHeaderTypedDict, XMag3ntEnvironment
    from .security import Security, SecurityTypedDict
    from .transaction import (
        Protocol,
        Transaction,
        TransactionAmount,
        TransactionAmountTypedDict,
        TransactionTypedDict,
    )

__all__ = [
    "APIKey",
    "APIKeyStatus",
    "APIKeyTypedDict",
    "Balance",
    "BalanceAvailable",
    "BalanceAvailableTypedDict",
    "BalanceErrorAvailable",
    "BalanceErrorAvailableTypedDict",
    "BalanceTypedDict",
    "BalanceUnion",
    "BalanceUnionTypedDict",
    "Card",
    "CardStatus",
    "CardTypedDict",
    "LimitAmount",
    "LimitAmountTypedDict",
    "PayLink",
    "PayLinkAmount",
    "PayLinkAmountTypedDict",
    "PayLinkStatus",
    "PayLinkTypedDict",
    "PaymentHeader",
    "PaymentHeaderTypedDict",
    "Protocol",
    "Remaining",
    "RemainingTypedDict",
    "Requested",
    "RequestedTypedDict",
    "Security",
    "SecurityTypedDict",
    "SingleUse",
    "TotalAllocated",
    "TotalAllocatedTypedDict",
    "TotalFunded",
    "TotalFundedTypedDict",
    "TotalSpent",
    "TotalSpentTypedDict",
    "TotalWithdrawn",
    "TotalWithdrawnTypedDict",
    "Transaction",
    "TransactionAmount",
    "TransactionAmountTypedDict",
    "TransactionTypedDict",
    "XMag3ntEnvironment",
]

_dynamic_imports: dict[str, str] = {
    "APIKey": ".apikey",
    "APIKeyStatus": ".apikey",
    "APIKeyTypedDict": ".apikey",
    "Balance": ".balance",
    "BalanceAvailable": ".balance",
    "BalanceAvailableTypedDict": ".balance",
    "BalanceTypedDict": ".balance",
    "TotalAllocated": ".balance",
    "TotalAllocatedTypedDict": ".balance",
    "TotalFunded": ".balance",
    "TotalFundedTypedDict": ".balance",
    "TotalSpent": ".balance",
    "TotalSpentTypedDict": ".balance",
    "TotalWithdrawn": ".balance",
    "TotalWithdrawnTypedDict": ".balance",
    "BalanceErrorAvailable": ".balanceerror",
    "BalanceErrorAvailableTypedDict": ".balanceerror",
    "Requested": ".balanceerror",
    "RequestedTypedDict": ".balanceerror",
    "BalanceUnion": ".card",
    "BalanceUnionTypedDict": ".card",
    "Card": ".card",
    "CardStatus": ".card",
    "CardTypedDict": ".card",
    "LimitAmount": ".card",
    "LimitAmountTypedDict": ".card",
    "Remaining": ".card",
    "RemainingTypedDict": ".card",
    "SingleUse": ".card",
    "PayLink": ".paylink",
    "PayLinkAmount": ".paylink",
    "PayLinkAmountTypedDict": ".paylink",
    "PayLinkStatus": ".paylink",
    "PayLinkTypedDict": ".paylink",
    "PaymentHeader": ".paymentheader",
    "PaymentHeaderTypedDict": ".paymentheader",
    "XMag3ntEnvironment": ".paymentheader",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "Protocol": ".transaction",
    "Transaction": ".transaction",
    "TransactionAmount": ".transaction",
    "TransactionAmountTypedDict": ".transaction",
    "TransactionTypedDict": ".transaction",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
