"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import Any, TYPE_CHECKING

from mag3nt.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .apikey import APIKey, APIKeyStatus, APIKeyTypedDict
    from .balance import Balance, BalanceTypedDict
    from .card import Card, CardStatus, CardTypedDict, SingleUse
    from .paylink import PayLink, PayLinkStatus, PayLinkTypedDict
    from .paymentheader import PaymentHeader, PaymentHeaderTypedDict, XMag3ntEnvironment
    from .security import Security, SecurityTypedDict
    from .transaction import Protocol, Transaction, TransactionTypedDict

__all__ = [
    "APIKey",
    "APIKeyStatus",
    "APIKeyTypedDict",
    "Balance",
    "BalanceTypedDict",
    "Card",
    "CardStatus",
    "CardTypedDict",
    "PayLink",
    "PayLinkStatus",
    "PayLinkTypedDict",
    "PaymentHeader",
    "PaymentHeaderTypedDict",
    "Protocol",
    "Security",
    "SecurityTypedDict",
    "SingleUse",
    "Transaction",
    "TransactionTypedDict",
    "XMag3ntEnvironment",
]

_dynamic_imports: dict[str, str] = {
    "APIKey": ".apikey",
    "APIKeyStatus": ".apikey",
    "APIKeyTypedDict": ".apikey",
    "Balance": ".balance",
    "BalanceTypedDict": ".balance",
    "Card": ".card",
    "CardStatus": ".card",
    "CardTypedDict": ".card",
    "SingleUse": ".card",
    "PayLink": ".paylink",
    "PayLinkStatus": ".paylink",
    "PayLinkTypedDict": ".paylink",
    "PaymentHeader": ".paymentheader",
    "PaymentHeaderTypedDict": ".paymentheader",
    "XMag3ntEnvironment": ".paymentheader",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "Protocol": ".transaction",
    "Transaction": ".transaction",
    "TransactionTypedDict": ".transaction",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
