"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from mag3nt.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
    UnrecognizedStr,
)
from pydantic import model_serializer
from typing import Literal, Optional, Union
from typing_extensions import NotRequired, TypedDict


APIKeyStatus = Union[
    Literal[
        "active",
        "revoked",
    ],
    UnrecognizedStr,
]


class APIKeyTypedDict(TypedDict):
    key_hash: NotRequired[str]
    key_hint: NotRequired[str]
    status: NotRequired[APIKeyStatus]
    created_at: NotRequired[datetime]
    revoked_at: NotRequired[Nullable[datetime]]


class APIKey(BaseModel):
    key_hash: Optional[str] = None

    key_hint: Optional[str] = None

    status: Optional[APIKeyStatus] = None

    created_at: Optional[datetime] = None

    revoked_at: OptionalNullable[datetime] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["key_hash", "key_hint", "status", "created_at", "revoked_at"]
        )
        nullable_fields = set(["revoked_at"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
