"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Union
from typing_extensions import TypeAliasType


BalanceErrorAvailableTypedDict = TypeAliasType(
    "BalanceErrorAvailableTypedDict", Union[float, str]
)


BalanceErrorAvailable = TypeAliasType("BalanceErrorAvailable", Union[float, str])


RequestedTypedDict = TypeAliasType("RequestedTypedDict", Union[float, str])


Requested = TypeAliasType("Requested", Union[float, str])
