"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mag3nt.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class BalanceTypedDict(TypedDict):
    total_funded: NotRequired[float]
    total_allocated: NotRequired[float]
    total_spent: NotRequired[float]
    total_withdrawn: NotRequired[float]
    available: NotRequired[float]
    network: NotRequired[str]
    asset: NotRequired[str]


class Balance(BaseModel):
    total_funded: Optional[float] = None

    total_allocated: Optional[float] = None

    total_spent: Optional[float] = None

    total_withdrawn: Optional[float] = None

    available: Optional[float] = None

    network: Optional[str] = None

    asset: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "total_funded",
                "total_allocated",
                "total_spent",
                "total_withdrawn",
                "available",
                "network",
                "asset",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
