"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mag3nt.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


TotalFundedTypedDict = TypeAliasType("TotalFundedTypedDict", Union[float, str])


TotalFunded = TypeAliasType("TotalFunded", Union[float, str])


TotalAllocatedTypedDict = TypeAliasType("TotalAllocatedTypedDict", Union[float, str])


TotalAllocated = TypeAliasType("TotalAllocated", Union[float, str])


TotalSpentTypedDict = TypeAliasType("TotalSpentTypedDict", Union[float, str])


TotalSpent = TypeAliasType("TotalSpent", Union[float, str])


TotalWithdrawnTypedDict = TypeAliasType("TotalWithdrawnTypedDict", Union[float, str])


TotalWithdrawn = TypeAliasType("TotalWithdrawn", Union[float, str])


BalanceAvailableTypedDict = TypeAliasType(
    "BalanceAvailableTypedDict", Union[float, str]
)


BalanceAvailable = TypeAliasType("BalanceAvailable", Union[float, str])


class BalanceTypedDict(TypedDict):
    total_funded: NotRequired[TotalFundedTypedDict]
    total_allocated: NotRequired[TotalAllocatedTypedDict]
    total_spent: NotRequired[TotalSpentTypedDict]
    total_withdrawn: NotRequired[TotalWithdrawnTypedDict]
    available: NotRequired[BalanceAvailableTypedDict]
    network: NotRequired[str]
    asset: NotRequired[str]


class Balance(BaseModel):
    total_funded: Optional[TotalFunded] = None

    total_allocated: Optional[TotalAllocated] = None

    total_spent: Optional[TotalSpent] = None

    total_withdrawn: Optional[TotalWithdrawn] = None

    available: Optional[BalanceAvailable] = None

    network: Optional[str] = None

    asset: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "total_funded",
                "total_allocated",
                "total_spent",
                "total_withdrawn",
                "available",
                "network",
                "asset",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
