"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from mag3nt.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
    UnrecognizedInt,
    UnrecognizedStr,
)
from pydantic import model_serializer
from typing import Literal, Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


LimitAmountTypedDict = TypeAliasType("LimitAmountTypedDict", Union[float, str])


LimitAmount = TypeAliasType("LimitAmount", Union[float, str])


CardStatus = Union[
    Literal[
        "ACTIVE",
        "FROZEN",
        "EXPIRED",
        "USED",
        "PENDING_FUNDING",
        "FUNDING_FAILED",
    ],
    UnrecognizedStr,
]


SingleUse = Union[
    Literal[
        0,
        1,
    ],
    UnrecognizedInt,
]


BalanceUnionTypedDict = TypeAliasType("BalanceUnionTypedDict", Union[float, str])


BalanceUnion = TypeAliasType("BalanceUnion", Union[float, str])


RemainingTypedDict = TypeAliasType("RemainingTypedDict", Union[float, str])


Remaining = TypeAliasType("Remaining", Union[float, str])


class CardTypedDict(TypedDict):
    id: NotRequired[str]
    token: NotRequired[str]
    purpose: NotRequired[str]
    limit_amount: NotRequired[LimitAmountTypedDict]
    status: NotRequired[CardStatus]
    mcc_locks: NotRequired[str]
    single_use: NotRequired[SingleUse]
    expires_at: NotRequired[Nullable[datetime]]
    funding_network: NotRequired[str]
    funding_asset: NotRequired[str]
    wallet_address: NotRequired[str]
    balance: NotRequired[BalanceUnionTypedDict]
    remaining: NotRequired[RemainingTypedDict]
    created_at: NotRequired[datetime]


class Card(BaseModel):
    id: Optional[str] = None

    token: Optional[str] = None

    purpose: Optional[str] = None

    limit_amount: Optional[LimitAmount] = None

    status: Optional[CardStatus] = None

    mcc_locks: Optional[str] = None

    single_use: Optional[SingleUse] = None

    expires_at: OptionalNullable[datetime] = UNSET

    funding_network: Optional[str] = None

    funding_asset: Optional[str] = None

    wallet_address: Optional[str] = None

    balance: Optional[BalanceUnion] = None

    remaining: Optional[Remaining] = None

    created_at: Optional[datetime] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "id",
                "token",
                "purpose",
                "limit_amount",
                "status",
                "mcc_locks",
                "single_use",
                "expires_at",
                "funding_network",
                "funding_asset",
                "wallet_address",
                "balance",
                "remaining",
                "created_at",
            ]
        )
        nullable_fields = set(["expires_at"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
