"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from mag3nt.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
    UnrecognizedStr,
)
from pydantic import model_serializer
from typing import Literal, Optional, Union
from typing_extensions import NotRequired, TypedDict


PayLinkStatus = Union[
    Literal[
        "ACTIVE",
        "EXPIRED",
        "CANCELLED",
    ],
    UnrecognizedStr,
]


class PayLinkTypedDict(TypedDict):
    id: NotRequired[str]
    code: NotRequired[str]
    url: NotRequired[str]
    amount: NotRequired[Nullable[float]]
    asset: NotRequired[str]
    network: NotRequired[str]
    memo: NotRequired[str]
    status: NotRequired[PayLinkStatus]
    uses: NotRequired[int]
    max_uses: NotRequired[int]
    expires_at: NotRequired[Nullable[datetime]]
    qr_svg: NotRequired[str]


class PayLink(BaseModel):
    id: Optional[str] = None

    code: Optional[str] = None

    url: Optional[str] = None

    amount: OptionalNullable[float] = UNSET

    asset: Optional[str] = None

    network: Optional[str] = None

    memo: Optional[str] = None

    status: Optional[PayLinkStatus] = None

    uses: Optional[int] = None

    max_uses: Optional[int] = None

    expires_at: OptionalNullable[datetime] = UNSET

    qr_svg: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "id",
                "code",
                "url",
                "amount",
                "asset",
                "network",
                "memo",
                "status",
                "uses",
                "max_uses",
                "expires_at",
                "qr_svg",
            ]
        )
        nullable_fields = set(["amount", "expires_at"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
