"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mag3nt.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PaymentHeaderTypedDict(TypedDict):
    x_mag3nt_transaction: NotRequired[str]
    x_mag3nt_card: NotRequired[str]
    x_mag3nt_amount: NotRequired[str]
    x_mag3nt_protocol: NotRequired[str]


class PaymentHeader(BaseModel):
    x_mag3nt_transaction: Annotated[
        Optional[str], pydantic.Field(alias="X-mag3nt-Transaction")
    ] = None

    x_mag3nt_card: Annotated[Optional[str], pydantic.Field(alias="X-mag3nt-Card")] = (
        None
    )

    x_mag3nt_amount: Annotated[
        Optional[str], pydantic.Field(alias="X-mag3nt-Amount")
    ] = None

    x_mag3nt_protocol: Annotated[
        Optional[str], pydantic.Field(alias="X-mag3nt-Protocol")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "X-mag3nt-Transaction",
                "X-mag3nt-Card",
                "X-mag3nt-Amount",
                "X-mag3nt-Protocol",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    PaymentHeader.model_rebuild()
except NameError:
    pass
