"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mag3nt.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Literal, Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


Type = Literal["payment.settled",]


PaymentSettledEventProtocol = Literal[
    "x402",
    "ap2",
    "mpp",
]


Mode = Literal[
    "external_protocol",
    "protocol",
]


PaymentSettledEventAmountTypedDict = TypeAliasType(
    "PaymentSettledEventAmountTypedDict", Union[float, str]
)


PaymentSettledEventAmount = TypeAliasType(
    "PaymentSettledEventAmount", Union[float, str]
)


FeeTypedDict = TypeAliasType("FeeTypedDict", Union[float, str])


Fee = TypeAliasType("Fee", Union[float, str])


NetAmountTypedDict = TypeAliasType("NetAmountTypedDict", Union[float, str])


NetAmount = TypeAliasType("NetAmount", Union[float, str])


class DataTypedDict(TypedDict):
    settlement_id: NotRequired[str]
    pay_link_code: NotRequired[str]
    protocol: NotRequired[PaymentSettledEventProtocol]
    mode: NotRequired[Mode]
    amount: NotRequired[PaymentSettledEventAmountTypedDict]
    fee: NotRequired[FeeTypedDict]
    net_amount: NotRequired[NetAmountTypedDict]
    asset: NotRequired[str]
    network: NotRequired[str]
    tx_hash: NotRequired[Nullable[str]]
    receipt_id: NotRequired[Nullable[str]]
    receiver_card_id: NotRequired[str]
    memo: NotRequired[Nullable[str]]


class Data(BaseModel):
    settlement_id: Optional[str] = None

    pay_link_code: Optional[str] = None

    protocol: Optional[PaymentSettledEventProtocol] = None

    mode: Optional[Mode] = None

    amount: Optional[PaymentSettledEventAmount] = None

    fee: Optional[Fee] = None

    net_amount: Optional[NetAmount] = None

    asset: Optional[str] = None

    network: Optional[str] = None

    tx_hash: OptionalNullable[str] = UNSET

    receipt_id: OptionalNullable[str] = UNSET

    receiver_card_id: Optional[str] = None

    memo: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "settlement_id",
                "pay_link_code",
                "protocol",
                "mode",
                "amount",
                "fee",
                "net_amount",
                "asset",
                "network",
                "tx_hash",
                "receipt_id",
                "receiver_card_id",
                "memo",
            ]
        )
        nullable_fields = set(["tx_hash", "receipt_id", "memo"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class PaymentSettledEventTypedDict(TypedDict):
    r"""Body POSTed to a registered webhook when a pay link settles. Signed via the X-mag3nt-Signature header (t=<unix>,v1=<hex hmac-sha256 of `${t}.${rawBody}`>). Verify with your webhook secret before acting."""

    id: NotRequired[str]
    type: NotRequired[Type]
    created: NotRequired[int]
    r"""Unix timestamp (seconds)"""
    data: NotRequired[DataTypedDict]


class PaymentSettledEvent(BaseModel):
    r"""Body POSTed to a registered webhook when a pay link settles. Signed via the X-mag3nt-Signature header (t=<unix>,v1=<hex hmac-sha256 of `${t}.${rawBody}`>). Verify with your webhook secret before acting."""

    id: Optional[str] = None

    type: Optional[Type] = None

    created: Optional[int] = None
    r"""Unix timestamp (seconds)"""

    data: Optional[Data] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "type", "created", "data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
