"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from mag3nt.types import BaseModel, UNSET_SENTINEL, UnrecognizedStr
from pydantic import model_serializer
from typing import Literal, Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


TransactionAmountTypedDict = TypeAliasType(
    "TransactionAmountTypedDict", Union[float, str]
)


TransactionAmount = TypeAliasType("TransactionAmount", Union[float, str])


TransactionProtocol = Union[
    Literal[
        "x402",
        "ap2",
        "mpp",
    ],
    UnrecognizedStr,
]


class TransactionTypedDict(TypedDict):
    id: NotRequired[str]
    card_id: NotRequired[str]
    amount: NotRequired[TransactionAmountTypedDict]
    merchant: NotRequired[str]
    protocol: NotRequired[TransactionProtocol]
    status: NotRequired[str]
    tx_hash: NotRequired[str]
    network: NotRequired[str]
    created_at: NotRequired[datetime]


class Transaction(BaseModel):
    id: Optional[str] = None

    card_id: Optional[str] = None

    amount: Optional[TransactionAmount] = None

    merchant: Optional[str] = None

    protocol: Optional[TransactionProtocol] = None

    status: Optional[str] = None

    tx_hash: Optional[str] = None

    network: Optional[str] = None

    created_at: Optional[datetime] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "id",
                "card_id",
                "amount",
                "merchant",
                "protocol",
                "status",
                "tx_hash",
                "network",
                "created_at",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
