"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mag3nt.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class WebhookSecretTypedDict(TypedDict):
    r"""Returned ONLY when a webhook is created. The secret is used to verify the X-mag3nt-Signature header on delivered events and cannot be retrieved again."""

    id: NotRequired[str]
    url: NotRequired[str]
    description: NotRequired[str]
    status: NotRequired[str]
    secret: NotRequired[str]
    r"""HMAC signing secret (whsec_...). Store securely; shown once."""
    note: NotRequired[str]


class WebhookSecret(BaseModel):
    r"""Returned ONLY when a webhook is created. The secret is used to verify the X-mag3nt-Signature header on delivered events and cannot be retrieved again."""

    id: Optional[str] = None

    url: Optional[str] = None

    description: Optional[str] = None

    status: Optional[str] = None

    secret: Optional[str] = None
    r"""HMAC signing secret (whsec_...). Store securely; shown once."""

    note: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "url", "description", "status", "secret", "note"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
