"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from mag3nt.types import BaseModel, UNSET_SENTINEL, UnrecognizedStr
from pydantic import model_serializer
from typing import Literal, Optional, Union
from typing_extensions import NotRequired, TypedDict


WebhookStatus = Union[
    Literal[
        "ACTIVE",
        "DISABLED",
    ],
    UnrecognizedStr,
]


class WebhookTypedDict(TypedDict):
    id: NotRequired[str]
    url: NotRequired[str]
    description: NotRequired[str]
    status: NotRequired[WebhookStatus]
    created_at: NotRequired[datetime]


class Webhook(BaseModel):
    id: Optional[str] = None

    url: Optional[str] = None

    description: Optional[str] = None

    status: Optional[WebhookStatus] = None

    created_at: Optional[datetime] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "url", "description", "status", "created_at"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
