"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from mag3nt.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
    UnrecognizedStr,
)
from pydantic import model_serializer
from typing import Literal, Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


Chain = Union[
    Literal[
        "eip155",
        "solana",
    ],
    UnrecognizedStr,
]


WithdrawalAmountTypedDict = TypeAliasType(
    "WithdrawalAmountTypedDict", Union[float, str]
)
r"""Gross amount deducted from balance (includes fee)"""


WithdrawalAmount = TypeAliasType("WithdrawalAmount", Union[float, str])
r"""Gross amount deducted from balance (includes fee)"""


FeeAmountTypedDict = TypeAliasType("FeeAmountTypedDict", Union[float, str])
r"""Platform withdrawal fee"""


FeeAmount = TypeAliasType("FeeAmount", Union[float, str])
r"""Platform withdrawal fee"""


WithdrawalStatus = Union[
    Literal[
        "PROCESSING",
        "COMPLETED",
        "FAILED",
    ],
    UnrecognizedStr,
]


class WithdrawalTypedDict(TypedDict):
    id: NotRequired[str]
    wallet_address: NotRequired[str]
    chain: NotRequired[Chain]
    asset: NotRequired[str]
    network: NotRequired[str]
    amount: NotRequired[WithdrawalAmountTypedDict]
    r"""Gross amount deducted from balance (includes fee)"""
    fee_amount: NotRequired[FeeAmountTypedDict]
    r"""Platform withdrawal fee"""
    to_address: NotRequired[str]
    status: NotRequired[WithdrawalStatus]
    tx_hash: NotRequired[Nullable[str]]
    r"""On-chain transaction hash (populated on completion)"""
    created_at: NotRequired[datetime]


class Withdrawal(BaseModel):
    id: Optional[str] = None

    wallet_address: Optional[str] = None

    chain: Optional[Chain] = None

    asset: Optional[str] = None

    network: Optional[str] = None

    amount: Optional[WithdrawalAmount] = None
    r"""Gross amount deducted from balance (includes fee)"""

    fee_amount: Optional[FeeAmount] = None
    r"""Platform withdrawal fee"""

    to_address: Optional[str] = None

    status: Optional[WithdrawalStatus] = None

    tx_hash: OptionalNullable[str] = UNSET
    r"""On-chain transaction hash (populated on completion)"""

    created_at: Optional[datetime] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "id",
                "wallet_address",
                "chain",
                "asset",
                "network",
                "amount",
                "fee_amount",
                "to_address",
                "status",
                "tx_hash",
                "created_at",
            ]
        )
        nullable_fields = set(["tx_hash"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
