"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from mag3nt.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


Ap2CreateMandateAmountTypedDict = TypeAliasType(
    "Ap2CreateMandateAmountTypedDict", Union[float, str]
)


Ap2CreateMandateAmount = TypeAliasType("Ap2CreateMandateAmount", Union[float, str])


MaxAmountTypedDict = TypeAliasType("MaxAmountTypedDict", Union[float, str])


MaxAmount = TypeAliasType("MaxAmount", Union[float, str])


class Ap2CreateMandateRequestTypedDict(TypedDict):
    card_id: str
    card_token: str
    amount: Ap2CreateMandateAmountTypedDict
    merchant: str
    max_amount: NotRequired[MaxAmountTypedDict]
    expires_at: NotRequired[datetime]


class Ap2CreateMandateRequest(BaseModel):
    card_id: str

    card_token: str

    amount: Ap2CreateMandateAmount

    merchant: str

    max_amount: Optional[MaxAmount] = None

    expires_at: Optional[datetime] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["max_amount", "expires_at"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ContentsTypedDict(TypedDict):
    pass


class Contents(BaseModel):
    pass


class Ap2CreateMandateResponseTypedDict(TypedDict):
    r"""Mandate created"""

    mandate_id: NotRequired[str]
    type: NotRequired[str]
    contents: NotRequired[ContentsTypedDict]
    merchant_signature: NotRequired[str]
    ttl: NotRequired[str]
    protocol: NotRequired[str]


class Ap2CreateMandateResponse(BaseModel):
    r"""Mandate created"""

    mandate_id: Optional[str] = None

    type: Optional[str] = None

    contents: Optional[Contents] = None

    merchant_signature: Optional[str] = None

    ttl: Optional[str] = None

    protocol: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["mandate_id", "type", "contents", "merchant_signature", "ttl", "protocol"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
