"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mag3nt.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


Ap2ExecuteAmountTypedDict = TypeAliasType(
    "Ap2ExecuteAmountTypedDict", Union[float, str]
)


Ap2ExecuteAmount = TypeAliasType("Ap2ExecuteAmount", Union[float, str])


class Ap2ExecuteRequestTypedDict(TypedDict):
    card_id: str
    card_token: str
    amount: Ap2ExecuteAmountTypedDict
    mandate_id: NotRequired[str]


class Ap2ExecuteRequest(BaseModel):
    card_id: str

    card_token: str

    amount: Ap2ExecuteAmount

    mandate_id: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["mandate_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class Ap2ExecuteResponseTypedDict(TypedDict):
    r"""Payment executed"""

    success: NotRequired[bool]
    transaction_id: NotRequired[str]


class Ap2ExecuteResponse(BaseModel):
    r"""Payment executed"""

    success: Optional[bool] = None

    transaction_id: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "transaction_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
