"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mag3nt.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


Ap2ListPaymentMethodsAvailableTypedDict = TypeAliasType(
    "Ap2ListPaymentMethodsAvailableTypedDict", Union[float, str]
)


Ap2ListPaymentMethodsAvailable = TypeAliasType(
    "Ap2ListPaymentMethodsAvailable", Union[float, str]
)


class MethodTypedDict(TypedDict):
    type: NotRequired[str]
    card_id: NotRequired[str]
    available: NotRequired[Ap2ListPaymentMethodsAvailableTypedDict]


class Method(BaseModel):
    type: Optional[str] = None

    card_id: Optional[str] = None

    available: Optional[Ap2ListPaymentMethodsAvailable] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type", "card_id", "available"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class Ap2ListPaymentMethodsResponseTypedDict(TypedDict):
    r"""Payment methods"""

    methods: NotRequired[List[MethodTypedDict]]


class Ap2ListPaymentMethodsResponse(BaseModel):
    r"""Payment methods"""

    methods: Optional[List[Method]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["methods"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
