"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mag3nt.types import BaseModel, UNSET_SENTINEL
from mag3nt.utils import FieldMetadata, PathParamMetadata
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class Ap2ListMandatesRequestTypedDict(TypedDict):
    card_id: str


class Ap2ListMandatesRequest(BaseModel):
    card_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


class MandateTypedDict(TypedDict):
    mandate_id: NotRequired[str]
    merchant: NotRequired[str]
    amount: NotRequired[float]
    status: NotRequired[str]


class Mandate(BaseModel):
    mandate_id: Optional[str] = None

    merchant: Optional[str] = None

    amount: Optional[float] = None

    status: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["mandate_id", "merchant", "amount", "status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class Ap2ListMandatesResponseTypedDict(TypedDict):
    r"""Mandates list"""

    mandates: NotRequired[List[MandateTypedDict]]


class Ap2ListMandatesResponse(BaseModel):
    r"""Mandates list"""

    mandates: Optional[List[Mandate]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["mandates"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
