"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mag3nt.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


Ap2SettleAmountTypedDict = TypeAliasType("Ap2SettleAmountTypedDict", Union[float, str])


Ap2SettleAmount = TypeAliasType("Ap2SettleAmount", Union[float, str])


class Ap2SettleRequestTypedDict(TypedDict):
    payer_card_id: str
    payer_card_token: str
    receiver_card_id: str
    amount: Ap2SettleAmountTypedDict
    network: NotRequired[str]


class Ap2SettleRequest(BaseModel):
    payer_card_id: str

    payer_card_token: str

    receiver_card_id: str

    amount: Ap2SettleAmount

    network: Optional[str] = "eip155:8453"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["network"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class Ap2SettleResponseTypedDict(TypedDict):
    r"""Settlement complete"""

    success: NotRequired[bool]
    transaction_id: NotRequired[str]


class Ap2SettleResponse(BaseModel):
    r"""Settlement complete"""

    success: Optional[bool] = None

    transaction_id: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "transaction_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
