"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mag3nt.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


class Ap2SettleRequestTypedDict(TypedDict):
    pay_link_code: str
    r"""Code of the pay link being settled."""
    closed_mandate: str
    r"""Closed AP2 Payment Mandate (mandate.payment.1) as an SD-JWT."""
    card_token: str
    r"""Token of the payer card named by the mandate (authorizes the debit)."""
    open_mandate: NotRequired[str]
    r"""Optional open AP2 mandate; when present the open→closed chain is re-verified."""


class Ap2SettleRequest(BaseModel):
    pay_link_code: str
    r"""Code of the pay link being settled."""

    closed_mandate: str
    r"""Closed AP2 Payment Mandate (mandate.payment.1) as an SD-JWT."""

    card_token: str
    r"""Token of the payer card named by the mandate (authorizes the debit)."""

    open_mandate: Optional[str] = None
    r"""Optional open AP2 mandate; when present the open→closed chain is re-verified."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["open_mandate"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


Ap2SettleAmountTypedDict = TypeAliasType("Ap2SettleAmountTypedDict", Union[float, str])


Ap2SettleAmount = TypeAliasType("Ap2SettleAmount", Union[float, str])


FeeTypedDict = TypeAliasType("FeeTypedDict", Union[float, str])


Fee = TypeAliasType("Fee", Union[float, str])


Ap2SettleNetAmountTypedDict = TypeAliasType(
    "Ap2SettleNetAmountTypedDict", Union[float, str]
)


Ap2SettleNetAmount = TypeAliasType("Ap2SettleNetAmount", Union[float, str])


class Ap2SettleResponseBody1TypedDict(TypedDict):
    r"""Settlement complete"""

    status: NotRequired[str]
    r"""SETTLED, or ALREADY_SETTLED on idempotent replay."""
    protocol: NotRequired[str]
    settlement_id: NotRequired[str]
    mandate_id: NotRequired[str]
    r"""The mandate jti the settlement is keyed on."""
    pay_link_code: NotRequired[str]
    amount: NotRequired[Ap2SettleAmountTypedDict]
    fee: NotRequired[FeeTypedDict]
    net_amount: NotRequired[Ap2SettleNetAmountTypedDict]
    tx_hash: NotRequired[Nullable[str]]
    payee: NotRequired[str]


class Ap2SettleResponseBody1(BaseModel):
    r"""Settlement complete"""

    status: Optional[str] = None
    r"""SETTLED, or ALREADY_SETTLED on idempotent replay."""

    protocol: Optional[str] = None

    settlement_id: Optional[str] = None

    mandate_id: Optional[str] = None
    r"""The mandate jti the settlement is keyed on."""

    pay_link_code: Optional[str] = None

    amount: Optional[Ap2SettleAmount] = None

    fee: Optional[Fee] = None

    net_amount: Optional[Ap2SettleNetAmount] = None

    tx_hash: OptionalNullable[str] = UNSET

    payee: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "status",
                "protocol",
                "settlement_id",
                "mandate_id",
                "pay_link_code",
                "amount",
                "fee",
                "net_amount",
                "tx_hash",
                "payee",
            ]
        )
        nullable_fields = set(["tx_hash"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class Ap2SettleResponseBody2TypedDict(TypedDict):
    r"""Mandate already settled (idempotent replay)"""

    status: NotRequired[str]


class Ap2SettleResponseBody2(BaseModel):
    r"""Mandate already settled (idempotent replay)"""

    status: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


Ap2SettleResponseTypedDict = TypeAliasType(
    "Ap2SettleResponseTypedDict",
    Union[Ap2SettleResponseBody2TypedDict, Ap2SettleResponseBody1TypedDict],
)


Ap2SettleResponse = TypeAliasType(
    "Ap2SettleResponse", Union[Ap2SettleResponseBody2, Ap2SettleResponseBody1]
)
