"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mag3nt.models.components import card as components_card
from mag3nt.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class CardsCreateRequestTypedDict(TypedDict):
    purpose: str
    r"""Human-readable label for the card"""
    limit_amount: float
    r"""Maximum spend in USDC"""
    network: NotRequired[str]
    asset: NotRequired[str]
    tx_hash: NotRequired[str]
    r"""On-chain funding transaction hash (optional)"""
    mcc_locks: NotRequired[str]
    r"""Comma-separated merchant category codes"""
    single_use: NotRequired[bool]
    expires_in: NotRequired[float]
    r"""Hours until expiry (0 = never)"""


class CardsCreateRequest(BaseModel):
    purpose: str
    r"""Human-readable label for the card"""

    limit_amount: float
    r"""Maximum spend in USDC"""

    network: Optional[str] = "eip155:8453"

    asset: Optional[str] = "USDC"

    tx_hash: Optional[str] = None
    r"""On-chain funding transaction hash (optional)"""

    mcc_locks: Optional[str] = None
    r"""Comma-separated merchant category codes"""

    single_use: Optional[bool] = False

    expires_in: Optional[float] = None
    r"""Hours until expiry (0 = never)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["network", "asset", "tx_hash", "mcc_locks", "single_use", "expires_in"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class CardsCreateResponseTypedDict(TypedDict):
    r"""Card created"""

    success: NotRequired[bool]
    card: NotRequired[components_card.CardTypedDict]


class CardsCreateResponse(BaseModel):
    r"""Card created"""

    success: Optional[bool] = None

    card: Optional[components_card.Card] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "card"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
