"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mag3nt.models.components import card as components_card
from mag3nt.types import BaseModel, UNSET_SENTINEL
from mag3nt.utils import FieldMetadata, HeaderMetadata, RequestMetadata
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CardTypedDict(TypedDict):
    purpose: str
    limit_amount: float


class Card(BaseModel):
    purpose: str

    limit_amount: float


class CardsBulkCreateRequestBodyTypedDict(TypedDict):
    cards: List[CardTypedDict]
    network: NotRequired[str]
    asset: NotRequired[str]


class CardsBulkCreateRequestBody(BaseModel):
    cards: List[Card]

    network: Optional[str] = "eip155:8453"

    asset: Optional[str] = "USDC"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["network", "asset"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class CardsBulkCreateRequestTypedDict(TypedDict):
    body: CardsBulkCreateRequestBodyTypedDict
    idempotency_key: NotRequired[str]
    r"""Unique key to prevent duplicate bulk operations"""


class CardsBulkCreateRequest(BaseModel):
    body: Annotated[
        CardsBulkCreateRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    idempotency_key: Annotated[
        Optional[str],
        pydantic.Field(alias="Idempotency-Key"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = None
    r"""Unique key to prevent duplicate bulk operations"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["Idempotency-Key"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class CardsBulkCreateResponseTypedDict(TypedDict):
    r"""Cards created"""

    success: NotRequired[bool]
    cards: NotRequired[List[components_card.CardTypedDict]]
    total_allocated: NotRequired[float]


class CardsBulkCreateResponse(BaseModel):
    r"""Cards created"""

    success: Optional[bool] = None

    cards: Optional[List[components_card.Card]] = None

    total_allocated: Optional[float] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "cards", "total_allocated"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
