"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mag3nt.types import BaseModel, UNSET_SENTINEL
from mag3nt.utils import FieldMetadata, PathParamMetadata
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CardsFreezeRequestTypedDict(TypedDict):
    id: str


class CardsFreezeRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


class CardsFreezeResponseTypedDict(TypedDict):
    r"""Card frozen"""

    success: NotRequired[bool]
    card_id: NotRequired[str]
    status: NotRequired[str]


class CardsFreezeResponse(BaseModel):
    r"""Card frozen"""

    success: Optional[bool] = None

    card_id: Optional[str] = None

    status: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "card_id", "status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
