"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mag3nt.types import BaseModel, UNSET_SENTINEL
from mag3nt.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from pydantic import model_serializer
from typing import Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


CardsTopUpAmountTypedDict = TypeAliasType(
    "CardsTopUpAmountTypedDict", Union[float, str]
)
r"""Amount in USDC to add"""


CardsTopUpAmount = TypeAliasType("CardsTopUpAmount", Union[float, str])
r"""Amount in USDC to add"""


class CardsTopUpRequestBodyTypedDict(TypedDict):
    amount: CardsTopUpAmountTypedDict
    r"""Amount in USDC to add"""


class CardsTopUpRequestBody(BaseModel):
    amount: CardsTopUpAmount
    r"""Amount in USDC to add"""


class CardsTopUpRequestTypedDict(TypedDict):
    id: str
    body: CardsTopUpRequestBodyTypedDict


class CardsTopUpRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    body: Annotated[
        CardsTopUpRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


AddedTypedDict = TypeAliasType("AddedTypedDict", Union[float, str])


Added = TypeAliasType("Added", Union[float, str])


NewLimitTypedDict = TypeAliasType("NewLimitTypedDict", Union[float, str])


NewLimit = TypeAliasType("NewLimit", Union[float, str])


class CardsTopUpResponseTypedDict(TypedDict):
    r"""Card topped up"""

    success: NotRequired[bool]
    card_id: NotRequired[str]
    added: NotRequired[AddedTypedDict]
    new_limit: NotRequired[NewLimitTypedDict]


class CardsTopUpResponse(BaseModel):
    r"""Card topped up"""

    success: Optional[bool] = None

    card_id: Optional[str] = None

    added: Optional[Added] = None

    new_limit: Optional[NewLimit] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "card_id", "added", "new_limit"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
