"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mag3nt.types import BaseModel, UNSET_SENTINEL
from mag3nt.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CardsUpdateControlsRequestBodyTypedDict(TypedDict):
    mcc_locks: NotRequired[str]
    daily_limit: NotRequired[float]
    max_transaction: NotRequired[float]


class CardsUpdateControlsRequestBody(BaseModel):
    mcc_locks: Optional[str] = None

    daily_limit: Optional[float] = None

    max_transaction: Optional[float] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["mcc_locks", "daily_limit", "max_transaction"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class CardsUpdateControlsRequestTypedDict(TypedDict):
    id: str
    body: CardsUpdateControlsRequestBodyTypedDict


class CardsUpdateControlsRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    body: Annotated[
        CardsUpdateControlsRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class CardsUpdateControlsResponseTypedDict(TypedDict):
    r"""Controls updated"""

    success: NotRequired[bool]


class CardsUpdateControlsResponse(BaseModel):
    r"""Controls updated"""

    success: Optional[bool] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
