"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mag3nt.types import BaseModel
from mag3nt.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class CardsClaimRequestBodyTypedDict(TypedDict):
    token: str


class CardsClaimRequestBody(BaseModel):
    token: str


class CardsClaimRequestTypedDict(TypedDict):
    id: str
    body: CardsClaimRequestBodyTypedDict


class CardsClaimRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    body: Annotated[
        CardsClaimRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
