"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mag3nt.models.components import balance as components_balance
from mag3nt.types import BaseModel, UNSET_SENTINEL, UnrecognizedStr
from pydantic import model_serializer
from typing import Literal, Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


class FundingVerifyRequestTypedDict(TypedDict):
    tx_hash: str
    r"""On-chain transaction hash to verify"""
    network: NotRequired[str]
    asset: NotRequired[str]


class FundingVerifyRequest(BaseModel):
    tx_hash: str
    r"""On-chain transaction hash to verify"""

    network: Optional[str] = "eip155:8453"

    asset: Optional[str] = "USDC"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["network", "asset"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


FundingVerifyStatus = Union[
    Literal[
        "confirmed",
        "pending",
    ],
    UnrecognizedStr,
]


FundedTypedDict = TypeAliasType("FundedTypedDict", Union[float, str])
r"""Amount credited from this transaction"""


Funded = TypeAliasType("Funded", Union[float, str])
r"""Amount credited from this transaction"""


class FundingVerifyResponseTypedDict(TypedDict):
    r"""Funding verified or pending"""

    success: NotRequired[bool]
    status: NotRequired[FundingVerifyStatus]
    funded: NotRequired[FundedTypedDict]
    r"""Amount credited from this transaction"""
    balance: NotRequired[components_balance.BalanceTypedDict]


class FundingVerifyResponse(BaseModel):
    r"""Funding verified or pending"""

    success: Optional[bool] = None

    status: Optional[FundingVerifyStatus] = None

    funded: Optional[Funded] = None
    r"""Amount credited from this transaction"""

    balance: Optional[components_balance.Balance] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "status", "funded", "balance"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
