"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mag3nt.types import BaseModel, UNSET_SENTINEL
from mag3nt.utils import FieldMetadata, QueryParamMetadata
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class FundingGetWalletBalanceRequestTypedDict(TypedDict):
    network: str
    asset: str
    address: NotRequired[str]
    r"""Wallet address (defaults to authenticated wallet)"""


class FundingGetWalletBalanceRequest(BaseModel):
    network: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]

    asset: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]

    address: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Wallet address (defaults to authenticated wallet)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["address"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class FundingGetWalletBalanceResponseTypedDict(TypedDict):
    r"""On-chain balance"""

    network: NotRequired[str]
    asset: NotRequired[str]
    address: NotRequired[str]
    balance: NotRequired[float]
    r"""Token balance in human units (e.g., 42.50 USDC)"""


class FundingGetWalletBalanceResponse(BaseModel):
    r"""On-chain balance"""

    network: Optional[str] = None

    asset: Optional[str] = None

    address: Optional[str] = None

    balance: Optional[float] = None
    r"""Token balance in human units (e.g., 42.50 USDC)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["network", "asset", "address", "balance"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
