"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from mag3nt.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class KeysValidateResponseTypedDict(TypedDict):
    r"""Key valid"""

    valid: NotRequired[bool]
    wallet_address: NotRequired[str]
    authenticated_at: NotRequired[datetime]


class KeysValidateResponse(BaseModel):
    r"""Key valid"""

    valid: Optional[bool] = None

    wallet_address: Optional[str] = None

    authenticated_at: Optional[datetime] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["valid", "wallet_address", "authenticated_at"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
