"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mag3nt.models.components import apikey as components_apikey
from mag3nt.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class KeysListResponseTypedDict(TypedDict):
    r"""Keys list"""

    keys: NotRequired[List[components_apikey.APIKeyTypedDict]]


class KeysListResponse(BaseModel):
    r"""Keys list"""

    keys: Optional[List[components_apikey.APIKey]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["keys"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
