"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mag3nt.types import BaseModel, UNSET_SENTINEL
from mag3nt.utils import FieldMetadata, PathParamMetadata
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class KeysRevokeRequestTypedDict(TypedDict):
    hash: str


class KeysRevokeRequest(BaseModel):
    hash: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


class KeysRevokeResponseTypedDict(TypedDict):
    r"""Key revoked"""

    success: NotRequired[bool]


class KeysRevokeResponse(BaseModel):
    r"""Key revoked"""

    success: Optional[bool] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
