"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mag3nt.types import BaseModel, UNSET_SENTINEL
from mag3nt.utils import FieldMetadata, QueryParamMetadata
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class MppDiscoverRequestTypedDict(TypedDict):
    url: str


class MppDiscoverRequest(BaseModel):
    url: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]


class CapabilitiesTypedDict(TypedDict):
    pass


class Capabilities(BaseModel):
    pass


class MppDiscoverResponseTypedDict(TypedDict):
    r"""Discovery result"""

    supports_mpp: NotRequired[bool]
    capabilities: NotRequired[CapabilitiesTypedDict]


class MppDiscoverResponse(BaseModel):
    r"""Discovery result"""

    supports_mpp: Optional[bool] = None

    capabilities: Optional[Capabilities] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["supports_mpp", "capabilities"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
