"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mag3nt.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class PaymentDataTypedDict(TypedDict):
    pass


class PaymentData(BaseModel):
    pass


class MppReceiveRequestTypedDict(TypedDict):
    payment_data: NotRequired[PaymentDataTypedDict]


class MppReceiveRequest(BaseModel):
    payment_data: Optional[PaymentData] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["payment_data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class MppReceiveResponseTypedDict(TypedDict):
    r"""Payment verified"""

    verified: NotRequired[bool]


class MppReceiveResponse(BaseModel):
    r"""Payment verified"""

    verified: Optional[bool] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["verified"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
