"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mag3nt.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


BudgetRequestTypedDict = TypeAliasType("BudgetRequestTypedDict", Union[float, str])
r"""Total budget for the stream in USDC"""


BudgetRequest = TypeAliasType("BudgetRequest", Union[float, str])
r"""Total budget for the stream in USDC"""


TickAmountRequestTypedDict = TypeAliasType(
    "TickAmountRequestTypedDict", Union[float, str]
)
r"""Amount per tick"""


TickAmountRequest = TypeAliasType("TickAmountRequest", Union[float, str])
r"""Amount per tick"""


class MppStreamsOpenRequestTypedDict(TypedDict):
    card_id: str
    card_token: str
    budget: BudgetRequestTypedDict
    r"""Total budget for the stream in USDC"""
    tick_amount: TickAmountRequestTypedDict
    r"""Amount per tick"""
    receiver_card_id: NotRequired[str]


class MppStreamsOpenRequest(BaseModel):
    card_id: str

    card_token: str

    budget: BudgetRequest
    r"""Total budget for the stream in USDC"""

    tick_amount: TickAmountRequest
    r"""Amount per tick"""

    receiver_card_id: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["receiver_card_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


MppStreamsOpenBudgetResponseTypedDict = TypeAliasType(
    "MppStreamsOpenBudgetResponseTypedDict", Union[float, str]
)


MppStreamsOpenBudgetResponse = TypeAliasType(
    "MppStreamsOpenBudgetResponse", Union[float, str]
)


MppStreamsOpenTickAmountResponseTypedDict = TypeAliasType(
    "MppStreamsOpenTickAmountResponseTypedDict", Union[float, str]
)


MppStreamsOpenTickAmountResponse = TypeAliasType(
    "MppStreamsOpenTickAmountResponse", Union[float, str]
)


MppStreamsOpenTotalTickedTypedDict = TypeAliasType(
    "MppStreamsOpenTotalTickedTypedDict", Union[float, str]
)


MppStreamsOpenTotalTicked = TypeAliasType(
    "MppStreamsOpenTotalTicked", Union[float, str]
)


class MppStreamsOpenResponseTypedDict(TypedDict):
    r"""Stream opened"""

    id: NotRequired[str]
    card_id: NotRequired[str]
    budget: NotRequired[MppStreamsOpenBudgetResponseTypedDict]
    tick_amount: NotRequired[MppStreamsOpenTickAmountResponseTypedDict]
    total_ticked: NotRequired[MppStreamsOpenTotalTickedTypedDict]
    status: NotRequired[str]
    receiver_card_id: NotRequired[str]


class MppStreamsOpenResponse(BaseModel):
    r"""Stream opened"""

    id: Optional[str] = None

    card_id: Optional[str] = None

    budget: Optional[MppStreamsOpenBudgetResponse] = None

    tick_amount: Optional[MppStreamsOpenTickAmountResponse] = None

    total_ticked: Optional[MppStreamsOpenTotalTicked] = None

    status: Optional[str] = None

    receiver_card_id: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "id",
                "card_id",
                "budget",
                "tick_amount",
                "total_ticked",
                "status",
                "receiver_card_id",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
