"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mag3nt.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class MppStreamsTickRequestTypedDict(TypedDict):
    stream_id: str
    card_id: str
    card_token: str


class MppStreamsTickRequest(BaseModel):
    stream_id: str

    card_id: str

    card_token: str


class MppStreamsTickResponseTypedDict(TypedDict):
    r"""Tick processed"""

    total_ticked: NotRequired[float]
    remaining: NotRequired[float]


class MppStreamsTickResponse(BaseModel):
    r"""Tick processed"""

    total_ticked: Optional[float] = None

    remaining: Optional[float] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["total_ticked", "remaining"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
