"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mag3nt.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class MppStreamsOpenRequestTypedDict(TypedDict):
    card_id: str
    card_token: str
    budget: float
    r"""Total budget for the stream in USDC"""
    tick_amount: float
    r"""Amount per tick"""
    receiver_card_id: NotRequired[str]


class MppStreamsOpenRequest(BaseModel):
    card_id: str

    card_token: str

    budget: float
    r"""Total budget for the stream in USDC"""

    tick_amount: float
    r"""Amount per tick"""

    receiver_card_id: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["receiver_card_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class MppStreamsOpenResponseTypedDict(TypedDict):
    r"""Stream opened"""

    id: NotRequired[str]
    card_id: NotRequired[str]
    budget: NotRequired[float]
    tick_amount: NotRequired[float]
    total_ticked: NotRequired[float]
    status: NotRequired[str]
    receiver_card_id: NotRequired[str]


class MppStreamsOpenResponse(BaseModel):
    r"""Stream opened"""

    id: Optional[str] = None

    card_id: Optional[str] = None

    budget: Optional[float] = None

    tick_amount: Optional[float] = None

    total_ticked: Optional[float] = None

    status: Optional[str] = None

    receiver_card_id: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "id",
                "card_id",
                "budget",
                "tick_amount",
                "total_ticked",
                "status",
                "receiver_card_id",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
