"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mag3nt.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class MppStreamsCloseRequestTypedDict(TypedDict):
    stream_id: str


class MppStreamsCloseRequest(BaseModel):
    stream_id: str


class MppStreamsCloseResponseTypedDict(TypedDict):
    r"""Stream closed"""

    final_amount: NotRequired[float]
    status: NotRequired[str]


class MppStreamsCloseResponse(BaseModel):
    r"""Stream closed"""

    final_amount: Optional[float] = None

    status: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["final_amount", "status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
