"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mag3nt.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


class MppStreamsTickRequestTypedDict(TypedDict):
    stream_id: str
    card_id: str
    card_token: str


class MppStreamsTickRequest(BaseModel):
    stream_id: str

    card_id: str

    card_token: str


MppStreamsTickTotalTickedTypedDict = TypeAliasType(
    "MppStreamsTickTotalTickedTypedDict", Union[float, str]
)


MppStreamsTickTotalTicked = TypeAliasType(
    "MppStreamsTickTotalTicked", Union[float, str]
)


RemainingTypedDict = TypeAliasType("RemainingTypedDict", Union[float, str])


Remaining = TypeAliasType("Remaining", Union[float, str])


class MppStreamsTickResponseTypedDict(TypedDict):
    r"""Tick processed"""

    total_ticked: NotRequired[MppStreamsTickTotalTickedTypedDict]
    remaining: NotRequired[RemainingTypedDict]


class MppStreamsTickResponse(BaseModel):
    r"""Tick processed"""

    total_ticked: Optional[MppStreamsTickTotalTicked] = None

    remaining: Optional[Remaining] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["total_ticked", "remaining"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
