"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mag3nt.types import BaseModel, UNSET_SENTINEL
from mag3nt.utils import FieldMetadata, PathParamMetadata
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PayLinksPrepareRequestTypedDict(TypedDict):
    code: str


class PayLinksPrepareRequest(BaseModel):
    code: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


class PayLinksPrepareResponseTypedDict(TypedDict):
    r"""Payment intent"""

    intent: NotRequired[str]
    accepted_protocols: NotRequired[List[str]]
    treasury_address: NotRequired[str]
    token_contract: NotRequired[str]


class PayLinksPrepareResponse(BaseModel):
    r"""Payment intent"""

    intent: Optional[str] = None

    accepted_protocols: Optional[List[str]] = None

    treasury_address: Optional[str] = None

    token_contract: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["intent", "accepted_protocols", "treasury_address", "token_contract"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
