"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mag3nt.types import BaseModel
from mag3nt.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class PayLinksGetRequestTypedDict(TypedDict):
    code: str


class PayLinksGetRequest(BaseModel):
    code: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
