"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mag3nt.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Literal, Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


PayLinksCreateAmountTypedDict = TypeAliasType(
    "PayLinksCreateAmountTypedDict", Union[str, float]
)
r"""Fixed amount (null for open-amount)"""


PayLinksCreateAmount = TypeAliasType("PayLinksCreateAmount", Union[str, float])
r"""Fixed amount (null for open-amount)"""


PayLinksCreateType = Literal[
    "SINGLE",
    "RECURRING",
]
r"""SINGLE for one-time, RECURRING for multi-use"""


class PayLinksCreateRequestTypedDict(TypedDict):
    card_id: str
    amount: NotRequired[Nullable[PayLinksCreateAmountTypedDict]]
    r"""Fixed amount (null for open-amount)"""
    memo: NotRequired[str]
    accepted_protocols: NotRequired[List[str]]
    type: NotRequired[PayLinksCreateType]
    r"""SINGLE for one-time, RECURRING for multi-use"""
    max_uses: NotRequired[int]
    expires_in: NotRequired[float]
    r"""Hours until expiry"""


class PayLinksCreateRequest(BaseModel):
    card_id: str

    amount: OptionalNullable[PayLinksCreateAmount] = UNSET
    r"""Fixed amount (null for open-amount)"""

    memo: Optional[str] = None

    accepted_protocols: Optional[List[str]] = None

    type: Optional[PayLinksCreateType] = "SINGLE"
    r"""SINGLE for one-time, RECURRING for multi-use"""

    max_uses: Optional[int] = 1

    expires_in: Optional[float] = None
    r"""Hours until expiry"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["amount", "memo", "accepted_protocols", "type", "max_uses", "expires_in"]
        )
        nullable_fields = set(["amount"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
