"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mag3nt.types import BaseModel, UNSET_SENTINEL, UnrecognizedStr
from mag3nt.utils import FieldMetadata, PathParamMetadata
from pydantic import model_serializer
from typing import Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


class PayLinksResolveRequestTypedDict(TypedDict):
    code: str


class PayLinksResolveRequest(BaseModel):
    code: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


PayLinksResolveType = Union[
    Literal[
        "receive",
        "merchant",
    ],
    UnrecognizedStr,
]


class PayLinksResolveResponseTypedDict(TypedDict):
    r"""Resolved data"""

    type: NotRequired[PayLinksResolveType]


class PayLinksResolveResponse(BaseModel):
    r"""Resolved data"""

    type: Optional[PayLinksResolveType] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
