"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from mag3nt.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from mag3nt.utils import FieldMetadata, PathParamMetadata
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PayLinksGetStatusRequestTypedDict(TypedDict):
    code: str


class PayLinksGetStatusRequest(BaseModel):
    code: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


class PayLinksGetStatusResponseTypedDict(TypedDict):
    r"""Status"""

    status: NotRequired[str]
    confirmed_at: NotRequired[Nullable[datetime]]


class PayLinksGetStatusResponse(BaseModel):
    r"""Status"""

    status: Optional[str] = None

    confirmed_at: OptionalNullable[datetime] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["status", "confirmed_at"])
        nullable_fields = set(["confirmed_at"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
