"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from mag3nt.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from mag3nt.utils import FieldMetadata, PathParamMetadata
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class SettlementGetStatusRequestTypedDict(TypedDict):
    txn_id: str


class SettlementGetStatusRequest(BaseModel):
    txn_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


class SettlementGetStatusResponseTypedDict(TypedDict):
    r"""Settlement status"""

    transaction_id: NotRequired[str]
    status: NotRequired[str]
    tx_hash: NotRequired[Nullable[str]]
    settled_at: NotRequired[Nullable[datetime]]


class SettlementGetStatusResponse(BaseModel):
    r"""Settlement status"""

    transaction_id: Optional[str] = None

    status: Optional[str] = None

    tx_hash: OptionalNullable[str] = UNSET

    settled_at: OptionalNullable[datetime] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["transaction_id", "status", "tx_hash", "settled_at"])
        nullable_fields = set(["tx_hash", "settled_at"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
