"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mag3nt.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class X402TypedDict(TypedDict):
    status: NotRequired[str]
    direction: NotRequired[str]
    spend: NotRequired[str]
    receive: NotRequired[str]
    discovery: NotRequired[str]
    networks: NotRequired[List[str]]
    schemes: NotRequired[List[str]]


class X402(BaseModel):
    status: Optional[str] = None

    direction: Optional[str] = None

    spend: Optional[str] = None

    receive: Optional[str] = None

    discovery: Optional[str] = None

    networks: Optional[List[str]] = None

    schemes: Optional[List[str]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "status",
                "direction",
                "spend",
                "receive",
                "discovery",
                "networks",
                "schemes",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class Ap2TypedDict(TypedDict):
    status: NotRequired[str]
    direction: NotRequired[str]
    spend: NotRequired[str]
    receive: NotRequired[str]


class Ap2(BaseModel):
    status: Optional[str] = None

    direction: Optional[str] = None

    spend: Optional[str] = None

    receive: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["status", "direction", "spend", "receive"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class MppTypedDict(TypedDict):
    status: NotRequired[str]
    direction: NotRequired[str]
    spend: NotRequired[str]
    receive: NotRequired[str]
    capabilities: NotRequired[List[str]]


class Mpp(BaseModel):
    status: Optional[str] = None

    direction: Optional[str] = None

    spend: Optional[str] = None

    receive: Optional[str] = None

    capabilities: Optional[List[str]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["status", "direction", "spend", "receive", "capabilities"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class StatusGetSettlementTypedDict(TypedDict):
    status: NotRequired[str]
    fee_model: NotRequired[str]
    engine: NotRequired[str]
    supported_networks: NotRequired[List[str]]


class StatusGetSettlement(BaseModel):
    status: Optional[str] = None

    fee_model: Optional[str] = None

    engine: Optional[str] = None

    supported_networks: Optional[List[str]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["status", "fee_model", "engine", "supported_networks"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ProtocolsTypedDict(TypedDict):
    x402: NotRequired[X402TypedDict]
    ap2: NotRequired[Ap2TypedDict]
    mpp: NotRequired[MppTypedDict]
    settlement: NotRequired[StatusGetSettlementTypedDict]


class Protocols(BaseModel):
    x402: Optional[X402] = None

    ap2: Optional[Ap2] = None

    mpp: Optional[Mpp] = None

    settlement: Optional[StatusGetSettlement] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["x402", "ap2", "mpp", "settlement"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class CardControlsTypedDict(TypedDict):
    mcc_locks: NotRequired[bool]
    single_use: NotRequired[bool]
    freeze_unfreeze: NotRequired[bool]
    spending_limits: NotRequired[bool]


class CardControls(BaseModel):
    mcc_locks: Optional[bool] = None

    single_use: Optional[bool] = None

    freeze_unfreeze: Optional[bool] = None

    spending_limits: Optional[bool] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["mcc_locks", "single_use", "freeze_unfreeze", "spending_limits"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class StatusGetResponseTypedDict(TypedDict):
    r"""Platform status and protocol manifest"""

    platform: NotRequired[str]
    version: NotRequired[str]
    model: NotRequired[str]
    protocols: NotRequired[ProtocolsTypedDict]
    card_controls: NotRequired[CardControlsTypedDict]


class StatusGetResponse(BaseModel):
    r"""Platform status and protocol manifest"""

    platform: Optional[str] = None

    version: Optional[str] = None

    model: Optional[str] = None

    protocols: Optional[Protocols] = None

    card_controls: Optional[CardControls] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["platform", "version", "model", "protocols", "card_controls"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
