"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mag3nt.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class TreasuryTypedDict(TypedDict):
    evm: NotRequired[str]
    solana: NotRequired[str]


class Treasury(BaseModel):
    evm: Optional[str] = None

    solana: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["evm", "solana"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class TokensTypedDict(TypedDict):
    pass


class Tokens(BaseModel):
    pass


class StatusGetConfigResponseTypedDict(TypedDict):
    r"""Configuration"""

    treasury: NotRequired[TreasuryTypedDict]
    tokens: NotRequired[TokensTypedDict]


class StatusGetConfigResponse(BaseModel):
    r"""Configuration"""

    treasury: Optional[Treasury] = None

    tokens: Optional[Tokens] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["treasury", "tokens"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
