"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mag3nt.models.components import withdrawal as components_withdrawal
from mag3nt.types import BaseModel, UNSET_SENTINEL
from mag3nt.utils import FieldMetadata, QueryParamMetadata
from pydantic import model_serializer
from typing import List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


WithdrawalsListStatus = Literal[
    "PROCESSING",
    "COMPLETED",
    "FAILED",
]
r"""Filter by status"""


class WithdrawalsListRequestTypedDict(TypedDict):
    id: NotRequired[str]
    r"""Look up a single withdrawal by ID"""
    status: NotRequired[WithdrawalsListStatus]
    r"""Filter by status"""


class WithdrawalsListRequest(BaseModel):
    id: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Look up a single withdrawal by ID"""

    status: Annotated[
        Optional[WithdrawalsListStatus],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter by status"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class WithdrawalsListResponseTypedDict(TypedDict):
    r"""Withdrawals list"""

    withdrawals: NotRequired[List[components_withdrawal.WithdrawalTypedDict]]


class WithdrawalsListResponse(BaseModel):
    r"""Withdrawals list"""

    withdrawals: Optional[List[components_withdrawal.Withdrawal]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["withdrawals"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
