"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mag3nt.types import BaseModel, UNSET_SENTINEL
from mag3nt.utils import FieldMetadata, QueryParamMetadata
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class X402DiscoverRequestTypedDict(TypedDict):
    url: str


class X402DiscoverRequest(BaseModel):
    url: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]


class X402DiscoverResponseTypedDict(TypedDict):
    r"""Discovery result"""

    supports_x402: NotRequired[bool]
    payment_address: NotRequired[str]
    amount: NotRequired[float]
    asset: NotRequired[str]


class X402DiscoverResponse(BaseModel):
    r"""Discovery result"""

    supports_x402: Optional[bool] = None

    payment_address: Optional[str] = None

    amount: Optional[float] = None

    asset: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["supports_x402", "payment_address", "amount", "asset"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
