"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mag3nt.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class PaymentHeaderTypedDict(TypedDict):
    pass


class PaymentHeader(BaseModel):
    pass


class X402ReceiveRequestTypedDict(TypedDict):
    payment_header: NotRequired[PaymentHeaderTypedDict]
    resource_url: NotRequired[str]


class X402ReceiveRequest(BaseModel):
    payment_header: Optional[PaymentHeader] = None

    resource_url: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["payment_header", "resource_url"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class X402ReceiveResponseTypedDict(TypedDict):
    r"""Payment verified"""

    verified: NotRequired[bool]
    resource: NotRequired[str]


class X402ReceiveResponse(BaseModel):
    r"""Payment verified"""

    verified: Optional[bool] = None

    resource: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["verified", "resource"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
