"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from mag3nt.models.components import paymentheader as components_paymentheader
from mag3nt.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
    UnrecognizedStr,
)
from pydantic import model_serializer
from typing import Literal, Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


X402PayAmountRequestTypedDict = TypeAliasType(
    "X402PayAmountRequestTypedDict", Union[float, str]
)
r"""Payment amount in USDC"""


X402PayAmountRequest = TypeAliasType("X402PayAmountRequest", Union[float, str])
r"""Payment amount in USDC"""


class X402PayRequestTypedDict(TypedDict):
    card_id: str
    r"""Card identifier (sx_...)"""
    card_token: str
    r"""Card secret token (tok_...)"""
    amount: X402PayAmountRequestTypedDict
    r"""Payment amount in USDC"""
    merchant: NotRequired[str]
    r"""Merchant identifier"""
    merchant_address: NotRequired[str]
    r"""Merchant wallet for settlement"""
    mcc: NotRequired[str]
    r"""Merchant category code"""
    resource_url: NotRequired[str]
    r"""URL being paid for"""
    network: NotRequired[str]


class X402PayRequest(BaseModel):
    card_id: str
    r"""Card identifier (sx_...)"""

    card_token: str
    r"""Card secret token (tok_...)"""

    amount: X402PayAmountRequest
    r"""Payment amount in USDC"""

    merchant: Optional[str] = None
    r"""Merchant identifier"""

    merchant_address: Optional[str] = None
    r"""Merchant wallet for settlement"""

    mcc: Optional[str] = None
    r"""Merchant category code"""

    resource_url: Optional[str] = None
    r"""URL being paid for"""

    network: Optional[str] = "eip155:8453"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["merchant", "merchant_address", "mcc", "resource_url", "network"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


X402PayAmountResponseTypedDict = TypeAliasType(
    "X402PayAmountResponseTypedDict", Union[float, str]
)


X402PayAmountResponse = TypeAliasType("X402PayAmountResponse", Union[float, str])


Environment = Union[
    Literal[
        "sandbox",
        "production",
    ],
    UnrecognizedStr,
]
r"""'sandbox' for testnet networks (e.g. eip155:84532), 'production' for mainnet. Sandbox transactions deduct balance but are never settled on-chain."""


class X402PayResponseTypedDict(TypedDict):
    r"""Payment authorized"""

    success: NotRequired[bool]
    transaction_id: NotRequired[str]
    card_id: NotRequired[str]
    amount: NotRequired[X402PayAmountResponseTypedDict]
    network: NotRequired[str]
    environment: NotRequired[Environment]
    r"""'sandbox' for testnet networks (e.g. eip155:84532), 'production' for mainnet. Sandbox transactions deduct balance but are never settled on-chain."""
    resource_url: NotRequired[Nullable[str]]
    protocol: NotRequired[str]
    timestamp: NotRequired[datetime]
    payment_header: NotRequired[components_paymentheader.PaymentHeaderTypedDict]


class X402PayResponse(BaseModel):
    r"""Payment authorized"""

    success: Optional[bool] = None

    transaction_id: Optional[str] = None

    card_id: Optional[str] = None

    amount: Optional[X402PayAmountResponse] = None

    network: Optional[str] = None

    environment: Optional[Environment] = None
    r"""'sandbox' for testnet networks (e.g. eip155:84532), 'production' for mainnet. Sandbox transactions deduct balance but are never settled on-chain."""

    resource_url: OptionalNullable[str] = UNSET

    protocol: Optional[str] = None

    timestamp: Optional[datetime] = None

    payment_header: Optional[components_paymentheader.PaymentHeader] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "success",
                "transaction_id",
                "card_id",
                "amount",
                "network",
                "environment",
                "resource_url",
                "protocol",
                "timestamp",
                "payment_header",
            ]
        )
        nullable_fields = set(["resource_url"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
