"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .mag3nterror import Mag3ntError
from typing import Any, TYPE_CHECKING

from mag3nt.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .balanceerror import BalanceError, BalanceErrorData
    from .error import Error, ErrorData
    from .mag3ntdefaulterror import Mag3ntDefaultError
    from .no_response_error import NoResponseError
    from .responsevalidationerror import ResponseValidationError

__all__ = [
    "BalanceError",
    "BalanceErrorData",
    "Error",
    "ErrorData",
    "Mag3ntDefaultError",
    "Mag3ntError",
    "NoResponseError",
    "ResponseValidationError",
]

_dynamic_imports: dict[str, str] = {
    "BalanceError": ".balanceerror",
    "BalanceErrorData": ".balanceerror",
    "Error": ".error",
    "ErrorData": ".error",
    "Mag3ntDefaultError": ".mag3ntdefaulterror",
    "NoResponseError": ".no_response_error",
    "ResponseValidationError": ".responsevalidationerror",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
