"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .mag3nterror import Mag3ntError
from typing import Any, TYPE_CHECKING

from mag3nt.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .balanceerror import BalanceError, BalanceErrorData
    from .error import Error, ErrorData
    from .mag3ntdefaulterror import Mag3ntDefaultError
    from .mpppay import MppPayGoneError, MppPayGoneErrorData
    from .no_response_error import NoResponseError
    from .paylinksgetstatus import (
        PayLinksGetStatusGoneError,
        PayLinksGetStatusGoneErrorData,
    )
    from .responsevalidationerror import ResponseValidationError
    from .withdrawalscreate import (
        BadRequestError,
        BadRequestErrorData,
        ForbiddenError,
        ForbiddenErrorData,
    )
    from .x402pay import X402PayGoneError, X402PayGoneErrorData

__all__ = [
    "BadRequestError",
    "BadRequestErrorData",
    "BalanceError",
    "BalanceErrorData",
    "Error",
    "ErrorData",
    "ForbiddenError",
    "ForbiddenErrorData",
    "Mag3ntDefaultError",
    "Mag3ntError",
    "MppPayGoneError",
    "MppPayGoneErrorData",
    "NoResponseError",
    "PayLinksGetStatusGoneError",
    "PayLinksGetStatusGoneErrorData",
    "ResponseValidationError",
    "X402PayGoneError",
    "X402PayGoneErrorData",
]

_dynamic_imports: dict[str, str] = {
    "BalanceError": ".balanceerror",
    "BalanceErrorData": ".balanceerror",
    "Error": ".error",
    "ErrorData": ".error",
    "Mag3ntDefaultError": ".mag3ntdefaulterror",
    "MppPayGoneError": ".mpppay",
    "MppPayGoneErrorData": ".mpppay",
    "NoResponseError": ".no_response_error",
    "PayLinksGetStatusGoneError": ".paylinksgetstatus",
    "PayLinksGetStatusGoneErrorData": ".paylinksgetstatus",
    "ResponseValidationError": ".responsevalidationerror",
    "BadRequestError": ".withdrawalscreate",
    "BadRequestErrorData": ".withdrawalscreate",
    "ForbiddenError": ".withdrawalscreate",
    "ForbiddenErrorData": ".withdrawalscreate",
    "X402PayGoneError": ".x402pay",
    "X402PayGoneErrorData": ".x402pay",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
