"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
from mag3nt.models.errors import Mag3ntError
from mag3nt.types import BaseModel
from typing import Optional


class BalanceErrorData(BaseModel):
    error: str
    available: float
    requested: float
    network: Optional[str] = None
    asset: Optional[str] = None


@dataclass(unsafe_hash=True)
class BalanceError(Mag3ntError):
    data: BalanceErrorData = field(hash=False)

    def __init__(
        self,
        data: BalanceErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
