"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
from mag3nt.models.errors import Mag3ntError
from mag3nt.types import BaseModel
from typing import Optional


class GoneErrorData(BaseModel):
    status: Optional[str] = None
    error: Optional[str] = None


@dataclass(unsafe_hash=True)
class GoneError(Mag3ntError):
    r"""Pay link has been used"""

    data: GoneErrorData = field(hash=False)

    def __init__(
        self,
        data: GoneErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
