"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import importlib.metadata

__title__: str = "mag3nt"
__version__: str = "0.1.2"
__openapi_doc_version__: str = "2026-05-22"
__gen_version__: str = "2.885.0"
__user_agent__: str = "speakeasy-sdk/python 0.1.2 2.885.0 2026-05-22 mag3nt"

try:
    if __package__ is not None:
        __version__ = importlib.metadata.version(__package__)
except importlib.metadata.PackageNotFoundError:
    pass
