"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from mag3nt import models, utils
from mag3nt._hooks import HookContext
from mag3nt.types import OptionalNullable, UNSET
from mag3nt.utils.unmarshal_json_response import unmarshal_json_response
from typing import Mapping, Optional, Union


class Payments(BaseSDK):
    r"""Universal outbound protocol payments"""

    def payments_execute(
        self,
        *,
        card_id: str,
        card_token: str,
        url: str,
        method: Optional[str] = "POST",
        body: Optional[
            Union[models.operations.Body, models.operations.BodyTypedDict]
        ] = None,
        headers: Optional[
            Union[models.operations.Headers, models.operations.HeadersTypedDict]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.operations.PaymentsExecuteResponse:
        r"""Execute a universal outbound payment

        Enables any mag3nt card to pay any external x402, MPP, or AP2 endpoint in a single HTTP call. The engine automatically probes the target URL, detects the protocol, and settles on-chain.


        If set, this operation will use `api_key_auth` from the global security.

        :param card_id: Card identifier (sx_...)
        :param card_token: Card secret token (tok_...)
        :param url: The external payment-protected URL to pay
        :param method: HTTP method to use when probing the URL
        :param body: JSON request body to trigger a priced challenge
        :param headers: Optional headers for the probe request
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.operations.PaymentsExecuteRequest(
            card_id=card_id,
            card_token=card_token,
            url=url,
            method=method,
            body=utils.get_pydantic_model(body, Optional[models.operations.Body]),
            headers=utils.get_pydantic_model(
                headers, Optional[models.operations.Headers]
            ),
        )

        req = self._build_request(
            method="POST",
            path="/api/pay",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request, False, False, "json", models.operations.PaymentsExecuteRequest
            ),
            allow_empty_value=None,
            allowed_fields=["api_key_auth"],
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config
            else:
                retries = utils.RetryConfig(
                    "backoff", utils.BackoffStrategy(500, 60000, 1.5, 3600000), True
                )

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["5XX", "429"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="paymentsExecute",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.operations.PaymentsExecuteResponse, http_res
            )
        if utils.match_response(http_res, ["400", "403", "410", "422", "4XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models.errors.Mag3ntDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models.errors.Mag3ntDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise models.errors.Mag3ntDefaultError("Unexpected response received", http_res)

    async def payments_execute_async(
        self,
        *,
        card_id: str,
        card_token: str,
        url: str,
        method: Optional[str] = "POST",
        body: Optional[
            Union[models.operations.Body, models.operations.BodyTypedDict]
        ] = None,
        headers: Optional[
            Union[models.operations.Headers, models.operations.HeadersTypedDict]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.operations.PaymentsExecuteResponse:
        r"""Execute a universal outbound payment

        Enables any mag3nt card to pay any external x402, MPP, or AP2 endpoint in a single HTTP call. The engine automatically probes the target URL, detects the protocol, and settles on-chain.


        If set, this operation will use `api_key_auth` from the global security.

        :param card_id: Card identifier (sx_...)
        :param card_token: Card secret token (tok_...)
        :param url: The external payment-protected URL to pay
        :param method: HTTP method to use when probing the URL
        :param body: JSON request body to trigger a priced challenge
        :param headers: Optional headers for the probe request
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.operations.PaymentsExecuteRequest(
            card_id=card_id,
            card_token=card_token,
            url=url,
            method=method,
            body=utils.get_pydantic_model(body, Optional[models.operations.Body]),
            headers=utils.get_pydantic_model(
                headers, Optional[models.operations.Headers]
            ),
        )

        req = self._build_request_async(
            method="POST",
            path="/api/pay",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request, False, False, "json", models.operations.PaymentsExecuteRequest
            ),
            allow_empty_value=None,
            allowed_fields=["api_key_auth"],
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config
            else:
                retries = utils.RetryConfig(
                    "backoff", utils.BackoffStrategy(500, 60000, 1.5, 3600000), True
                )

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["5XX", "429"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="paymentsExecute",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.operations.PaymentsExecuteResponse, http_res
            )
        if utils.match_response(http_res, ["400", "403", "410", "422", "4XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models.errors.Mag3ntDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models.errors.Mag3ntDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise models.errors.Mag3ntDefaultError("Unexpected response received", http_res)
