"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from .httpclient import AsyncHttpClient, ClientOwner, HttpClient, close_clients
from .sdkconfiguration import SDKConfiguration
from .utils.logger import Logger, get_default_logger
from .utils.retries import RetryConfig
import httpx
import importlib
from mag3nt import models, utils
from mag3nt._hooks import SDKHooks
from mag3nt.types import OptionalNullable, UNSET
import sys
from typing import Any, Callable, Dict, Optional, TYPE_CHECKING, Union, cast
import weakref

if TYPE_CHECKING:
    from mag3nt.ap2 import Ap2
    from mag3nt.cards import Cards
    from mag3nt.funding import Funding
    from mag3nt.keys import Keys
    from mag3nt.mpp import Mpp
    from mag3nt.pay_links import PayLinks
    from mag3nt.payments import Payments
    from mag3nt.settlement import Settlement
    from mag3nt.status import Status
    from mag3nt.webhooks import Webhooks
    from mag3nt.withdrawals import Withdrawals
    from mag3nt.x402 import X402


class Mag3nt(BaseSDK):
    r"""mag3nt API: Payment infrastructure for AI agents. Issue virtual cards, pay for API access via x402/AP2/MPP protocols, and settle in USDC on Base.

    https://docs.mag3nt.com - mag3nt documentation
    """

    cards: "Cards"
    r"""Virtual payment card lifecycle"""
    keys: "Keys"
    r"""Developer API key management"""
    funding: "Funding"
    r"""Treasury deposits and balances"""
    withdrawals: "Withdrawals"
    r"""Withdraw unspent funds back to wallet"""
    payments: "Payments"
    r"""Universal outbound protocol payments"""
    x402: "X402"
    r"""HTTP 402 payment protocol"""
    status: "Status"
    r"""System health and configuration"""
    ap2: "Ap2"
    r"""Agent-to-Agent Payment Protocol"""
    mpp: "Mpp"
    r"""Micropayment Protocol with streaming"""
    pay_links: "PayLinks"
    r"""Shareable payment URLs"""
    settlement: "Settlement"
    r"""On-chain settlement status"""
    webhooks: "Webhooks"
    r"""Signed payment.settled notifications for sellers"""
    _sub_sdk_map = {
        "cards": ("mag3nt.cards", "Cards"),
        "keys": ("mag3nt.keys", "Keys"),
        "funding": ("mag3nt.funding", "Funding"),
        "withdrawals": ("mag3nt.withdrawals", "Withdrawals"),
        "payments": ("mag3nt.payments", "Payments"),
        "x402": ("mag3nt.x402", "X402"),
        "status": ("mag3nt.status", "Status"),
        "ap2": ("mag3nt.ap2", "Ap2"),
        "mpp": ("mag3nt.mpp", "Mpp"),
        "pay_links": ("mag3nt.pay_links", "PayLinks"),
        "settlement": ("mag3nt.settlement", "Settlement"),
        "webhooks": ("mag3nt.webhooks", "Webhooks"),
    }

    def __init__(
        self,
        api_key_auth: Optional[
            Union[Optional[str], Callable[[], Optional[str]]]
        ] = None,
        server_idx: Optional[int] = None,
        url_params: Optional[Dict[str, str]] = None,
        server_url: Optional[str] = None,
        client: Optional[HttpClient] = None,
        async_client: Optional[AsyncHttpClient] = None,
        retry_config: OptionalNullable[RetryConfig] = UNSET,
        timeout_ms: Optional[int] = None,
        debug_logger: Optional[Logger] = None,
    ) -> None:
        r"""Instantiates the SDK configuring it with the provided parameters.

        :param api_key_auth: The api_key_auth required for authentication
        :param server_idx: The index of the server to use for all methods
        :param server_url: The server URL to use for all methods
        :param url_params: Parameters to optionally template the server URL with
        :param client: The HTTP client to use for all synchronous methods
        :param async_client: The Async HTTP client to use for all asynchronous methods
        :param retry_config: The retry configuration to use for all supported methods
        :param timeout_ms: Optional request timeout applied to each operation in milliseconds
        """
        client_supplied = True
        if client is None:
            client = httpx.Client(follow_redirects=True)
            client_supplied = False

        assert issubclass(
            type(client), HttpClient
        ), "The provided client must implement the HttpClient protocol."

        async_client_supplied = True
        if async_client is None:
            async_client = httpx.AsyncClient(follow_redirects=True)
            async_client_supplied = False

        if debug_logger is None:
            debug_logger = get_default_logger()

        assert issubclass(
            type(async_client), AsyncHttpClient
        ), "The provided async_client must implement the AsyncHttpClient protocol."

        security: Any = None
        if api_key_auth is None:
            security = None
        elif callable(api_key_auth):
            # pylint: disable=unnecessary-lambda-assignment
            security = lambda: models.components.Security(api_key_auth=api_key_auth())
        else:
            security = models.components.Security(api_key_auth=api_key_auth)

        if server_url is not None:
            if url_params is not None:
                server_url = utils.template_url(server_url, url_params)

        BaseSDK.__init__(
            self,
            SDKConfiguration(
                client=client,
                client_supplied=client_supplied,
                async_client=async_client,
                async_client_supplied=async_client_supplied,
                security=security,
                server_url=server_url,
                server_idx=server_idx,
                retry_config=retry_config,
                timeout_ms=timeout_ms,
                debug_logger=debug_logger,
            ),
            parent_ref=self,
        )

        hooks = SDKHooks()

        # pylint: disable=protected-access
        self.sdk_configuration.__dict__["_hooks"] = hooks

        self.sdk_configuration = hooks.sdk_init(self.sdk_configuration)

        weakref.finalize(
            self,
            close_clients,
            cast(ClientOwner, self.sdk_configuration),
            self.sdk_configuration.client,
            self.sdk_configuration.client_supplied,
            self.sdk_configuration.async_client,
            self.sdk_configuration.async_client_supplied,
        )

    def dynamic_import(self, modname, retries=3):
        for attempt in range(retries):
            try:
                return importlib.import_module(modname)
            except KeyError:
                # Clear any half-initialized module and retry
                sys.modules.pop(modname, None)
                if attempt == retries - 1:
                    break
        raise KeyError(f"Failed to import module '{modname}' after {retries} attempts")

    def __getattr__(self, name: str):
        if name in self._sub_sdk_map:
            module_path, class_name = self._sub_sdk_map[name]
            try:
                module = self.dynamic_import(module_path)
                klass = getattr(module, class_name)
                instance = klass(self.sdk_configuration, parent_ref=self)
                setattr(self, name, instance)
                return instance
            except ImportError as e:
                raise AttributeError(
                    f"Failed to import module {module_path} for attribute {name}: {e}"
                ) from e
            except AttributeError as e:
                raise AttributeError(
                    f"Failed to find class {class_name} in module {module_path} for attribute {name}: {e}"
                ) from e

        raise AttributeError(
            f"'{type(self).__name__}' object has no attribute '{name}'"
        )

    def __dir__(self):
        default_attrs = list(super().__dir__())
        lazy_attrs = list(self._sub_sdk_map.keys())
        return sorted(list(set(default_attrs + lazy_attrs)))

    def __enter__(self):
        return self

    async def __aenter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        if (
            self.sdk_configuration.client is not None
            and not self.sdk_configuration.client_supplied
        ):
            self.sdk_configuration.client.close()
        self.sdk_configuration.client = None

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        if (
            self.sdk_configuration.async_client is not None
            and not self.sdk_configuration.async_client_supplied
        ):
            await self.sdk_configuration.async_client.aclose()
        self.sdk_configuration.async_client = None
